name: TruffleRuby Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  truffle-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CORE_EXT: gem
      RUBY_NEXT_CORE_STRATEGY: core_ext
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /home/runner/bundle
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby
    - name: Download MSpec
      run: |
        git clone https://github.com/ruby/mspec.git mspec
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-truffle-${{ hashFiles('../Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-truffle-
    - name: Bundle install
      run: |
        bundle install
    - name: Run MSpec Core
      run: |
        bundle install
        bundle exec mspec/bin/mspec :core
    - name: Run MSpec Integration
      env:
        COMMAND_DEBUG: true
      run: |
        bundle install
        bundle exec mspec/bin/mspec spec/integration/language_spec.rb
    # - name: Run language specs with source rewriting
    #   env:
    #     RUBY_NEXT_TRANSPILE_MODE: "rewrite"
    #   run: bundle exec mspec/bin/mspec :language
